# -*- coding: utf-8 -*-
"""novoenovo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VyP25N14V78plOmviggPnrTlgZWi_5oS
"""

# Nesse progama é possivel colocar o valor de um produto com seu desconto, e saber quanto fica, e tambem se o desconto esta bom.

# valor do produto e a porcentagem de desconto
n1 = float(input('coloque o valor do produto aqui: '))
n2 = float(input('coloque a porcentagem de desconto aqui: '))

# soma dos 2 valores para dar o resultado do desconto
soma = n1 - (n1 * n2) / 100

# mostra o preço do produto, o desconto, e por ultimo qual o preço do produto com o desconto
print(f'o produto que era R${n1} com o desconto de {n2}% ficou R${soma:.2f}')

# mostra se o produto esta com um bom desconto, abaixo de 500, 300 e 100 !
if soma > 500 :
    print('o preço esta altissimo mesmo com o desconto, não compre !')
elif soma > 300 :
    print(' o preço esta muito alto, espere um desconto melhor !')
elif soma > 100 :
    print("o desconto esta bom porem ainda esta caro !")
else:
    print('com esse desconto o preço o desconto esta bom, pode comprar !')