# -*- coding: utf-8 -*-
"""novoenovo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VyP25N14V78plOmviggPnrTlgZWi_5oS
"""

import tkinter as tk
from tkinter import messagebox

def check_answer():
    if selected_option.get() == 1:
        messagebox.showinfo("Resposta", "Correto!")
    else:
        messagebox.showinfo("Resposta", "Errado. A resposta correta é Picasso.")

# Configura a janela
window = tk.Tk()
window.title("Trivia Time")
window.geometry("300x200")

# Pergunta
question_label = tk.Label(window, text="Which painter was born in Spain?")
question_label.pack(pady=10)

# Opções
selected_option = tk.IntVar()
option1 = tk.Radiobutton(window, text="Picasso", variable=selected_option, value=1)
option2 = tk.Radiobutton(window, text="Matisse", variable=selected_option, value=2)

option1.pack()
option2.pack()

# Botão de submissão
submit_button = tk.Button(window, text="Submit", command=check_answer)
submit_button.pack(pady=20)

# Inicia o loop da interface
window.mainloop()